### ISSUE TITLE
Correct usage of fill command

### ISSUE THREAD

**Issue by yuki-uthman** [leonceaklin/real-turtle#2]
Hello, 

Thank you for the wonderful library! 
Really enjoying the animation.

I just wanted to ask about the fill command because I do not know how to use it.

So in canvas you can do something like this.

```
ctx.beginPath();
ctx.arc(100, 75, 50, 0, 2 * Math.PI);
ctx.fill()
```

But this does not seem to work.
```
turtle.beginPath()
turtle.arc(100, 360)
turtle.fill()
```

Am I doing it wrong?

I am sorry for taking your time.

**Comment by leonceaklin** [comment]
Hello,

glad you like it :)

Well, the sad truth is that the fill command is not yet working correctly. Under the hood, the library is just doing what you describe but because of the animations that require redrawing parts of the canvas, a simple ctx.fill() doesn't work there. Now that someone actually wants to use it, think I should finally make it work. Give me a few days to fix this.

**Comment by leonceaklin** [comment]
Ok now with version 1.0.17 fills are possible. I also added `.stroke()` which does the same thing as the native canvas `.stroke()`

**Comment by yuki-uthman** [comment]
Wow that was super fast!

I just tested out and it works perfect!

Thanks alot for your work!!!
